### ISSUE TITLE
Installation problem on CentOS7

### ISSUE THREAD

**Issue by lenkis** [tarantool/gis#1]
Can't install gis module on CentOS7 (in VirtualBox on Mac). Steps:
1) enable epel
``$ wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm``
``$ rpm -ivh epel-release-7-8.noarch.rpm``
2) install gis module: 
``$ sudo yum tarantool-gis proj-devel geos-devel``
2) launch tarantool with an app requiring gis module (game.lua app from https://github.com/Sulverus/pokemon):
``$ tarantool game.lua``
Error at launch: symbol lookup error: /usr/lib64/tarantool/gis/lib.so: undefined symbol: GEOS_init_r
3) install devel modules:
``$ sudo yum proj-devel geos-devel``
4) launch my tarantool instance again:
``$ tarantool game.lua``
Error at launch: symbol lookup error: /usr/lib64/tarantool/gis/lib.so: undefined symbol: GEOS_init_r

**Comment by Totktonada** [comment]
Works now. It seems that tarantool-gis package for CentOS 7 was built in some environment where libgeos_c.so has different set of symbols and the headers files are correspond. It seems that b0c2fb435aee5ce4b8ac79221ef37141aff1564a fixed that.
